# Generated by Django 5.1 on 2024-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutsection_counter_feedback_service_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('checklist', models.TextField()),
            ],
        ),
    ]
