# Generated by Django 5.1 on 2024-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_aboutsectionbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
