# Generated by Django 5.1 on 2024-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='eng_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
