# Generated by Django 5.1 on 2024-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_menu_eng_title_alter_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='eng_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
