# Generated by Django 5.1 on 2024-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_submenu_eng_title_alter_submenu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='eng_button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='eng_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutsectionbody',
            name='eng_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsectionbody',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
