# Generated by Django 5.1 on 2024-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_aboutsection_eng_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='eng_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='eng_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='eng_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='eng_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='eng_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
