# Generated by Django 5.1.2 on 2024-10-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_feedback_eng_name_service_eng_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('slot', models.CharField(choices=[('10:00-11:30', '10:00-11:30'), ('11:30-13:00', '11:30-13:00')], default='10:00-11:30', max_length=100)),
                ('total_person', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Réservé', 'Réservé'), ('Rejeté', 'Rejeté')], default='Réservé', max_length=10)),
            ],
        ),
    ]
