# Generated by Django 5.1.2 on 2024-10-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
