# Generated by Django 5.1.2 on 2024-10-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_reservation_total_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot',
            field=models.CharField(choices=[('10:00-11:30', '10:00-11:30'), ('11:30-13:00', '11:30-13:00'), ('13:00-14:30', '13:00-14:30'), ('14:30-16:00', '14:30-16:00'), ('16:00-17:30', '16:00-17:30'), ('17:30-19:00', '17:30-19:00'), ('19:00-20:30', '19:00-20:30'), ('20:30-22:00', '20:30-22:00')], default='10:00-11:30', max_length=100),
        ),
    ]
