# Generated by Django 5.1.2 on 2024-10-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_reservation_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_person',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
