# Generated by Django 5.1.2 on 2024-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_reservation_total_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice_slip',
            field=models.FileField(blank=True, null=True, upload_to='reservation/invoice_slip'),
        ),
    ]
