# Generated by Django 5.1.2 on 2024-10-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_reservation_invoice_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='invoice_slip',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
    ]
