# Generated by Django 5.1.2 on 2024-10-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_reservation_invoice_slip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='link',
        ),
        migrations.AddField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='emporter_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='eng_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='livraison_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='sur_place_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='eng_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='eng_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
