# Generated by Django 5.1.2 on 2024-10-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='background_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='background_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
