# Generated by Django 5.1.2 on 2024-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_aboutsection_background_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us/'),
        ),
    ]
