# Generated by Django 5.1.2 on 2024-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_aboutsection_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
