# Generated by Django 5.1.2 on 2024-10-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_operatinghour_openinghours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.DeleteModel(
            name='OperatingHour',
        ),
    ]
