# Generated by Django 5.1.2 on 2024-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_openinghours_operatinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='video_url',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opening_hours/'),
        ),
    ]
