# Generated by Django 5.1.2 on 2024-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_remove_openinghours_video_url_openinghours_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_position', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
