# Generated by Django 5.1.2 on 2024-11-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_siteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
