# Generated by Django 5.1.2 on 2024-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_remove_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_delivery_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
