# Generated by Django 5.1.2 on 2024-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_sitesettings_is_delivery_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='snapchat_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
