# Generated by Django 5.1.2 on 2024-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_siteinfo_snapchat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='pdf_menu',
            field=models.FileField(blank=True, null=True, upload_to='menu_pdf/'),
        ),
    ]
