# Generated by Django 5.1.2 on 2025-05-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_siteinfo_pdf_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot',
            field=models.CharField(choices=[('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('18:00-19:00', '18:00-19:00'), ('19:00-20:00', '19:00-20:00'), ('21:00-22:00', '21:00-22:00'), ('22:00-23:30', '22:00-23:30')], default='10:00-11:30', max_length=100),
        ),
    ]
