# Generated by Django 5.1.2 on 2025-12-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_alter_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_take_away_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
