# Generated by Django 5.1.2 on 2026-01-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_sitesettings_is_take_away_enabled'),
        ('shop', '0036_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='shop.cartorder'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
