# Generated by Django 5.1.2 on 2026-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_reservation_order_alter_reservation_total_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Réservé', 'Réservé'), ('Rejeté', 'Rejeté')], default='En attente', max_length=10),
        ),
    ]
