# Generated by Django 5.0.4 on 2024-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_quantity_address_cartorder_cartorderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
