# Generated by Django 5.1 on 2024-08-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartorderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
