# Generated by Django 5.0.4 on 2024-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
