# Generated by Django 5.0.4 on 2024-08-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_countdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.countdown'),
        ),
    ]
