# Generated by Django 5.1 on 2024-08-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_supercategory_category_super_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supercategory',
            options={'verbose_name_plural': 'Super Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_countdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.countdown'),
        ),
    ]
