# Generated by Django 5.1.2 on 2024-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_user_category_eng_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
