# Generated by Django 5.1.2 on 2024-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('take_away', 'Take Away'), ('pay_on_spot', 'Pay On Spot')], default='delivery', max_length=100),
        ),
    ]
