# Generated by Django 5.1.2 on 2024-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
