# Generated by Django 5.1.2 on 2024-10-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_cartorder_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Default shipping cost', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate as a percentage, e.g., 15 for 15%', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Cost Settings',
            },
        ),
    ]
