# Generated by Django 5.1.2 on 2024-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_cartorder_shipping_cost_cartorder_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
