# Generated by Django 5.1.2 on 2024-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_cartorder_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_applied',
            field=models.BooleanField(default=False),
        ),
    ]
