# Generated by Django 5.1.2 on 2024-11-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_tax_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='tax_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
