# Generated by Django 5.1.2 on 2024-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_cartorder_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
