# Generated by Django 5.1.2 on 2024-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_cartorder_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('progress', 'Order In Progress'), ('placed', 'Order Placed'), ('accepted', 'Order Accepted'), ('delivered', 'Order Delivered'), ('cancelled', 'Order Cancelled')], default='placed', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('progress', 'Order In Progress'), ('placed', 'Order Placed'), ('accepted', 'Order Accepted'), ('delivered', 'Order Delivered'), ('cancelled', 'Order Cancelled')], default='process', max_length=100),
        ),
    ]
