# Generated by Django 5.1.2 on 2024-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
