# Generated by Django 5.1.2 on 2024-11-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_countdown_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=99999999999, null=True),
        ),
    ]
