# Generated by Django 5.1.2 on 2024-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
