# Generated by Django 5.1.2 on 2025-12-21 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_product_offer_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='eng_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
